name: IP Test


on:

  schedule:

    # 每3小时运行

    - cron: '0 */3 * * *'


  workflow_dispatch:



jobs:


  collect-ips:


    runs-on: ubuntu-latest


    permissions:

      contents: write



    steps:



    # 拉取仓库

    - name: Checkout code

      uses: actions/checkout@v4





    # Python环境

    - name: Set up Python

      uses: actions/setup-python@v5

      with:

        python-version: '3.11'





    # 安装依赖

    - name: Install dependencies

      run: |

        python -m pip install --upgrade pip

        pip install requests urllib3





    # 运行Senflare

    - name: Run Senflare IP Test

      run: |

        python IPtest.py





    # 下载CloudflareSpeedTest

    - name: Install CloudflareSpeedTest

      run: |


        wget -N https://github.com/XIU2/CloudflareSpeedTest/releases/latest/download/cfst_linux_amd64.tar.gz


        tar -zxf cfst_linux_amd64.tar.gz



        echo "查看CFST文件"



        ls -al cfst_linux_amd64





    # Cloudflare测速

    - name: Run CloudflareSpeedTest

      run: |


        echo "准备IP列表"



        cp IPlist-Pro.txt ip.txt



        echo "开始测速"



        chmod +x cfst_linux_amd64/cfst



        ./cfst_linux_amd64/cfst \
        -f ip.txt \
        -o result.csv \
        -t 20





    # 自动更新Cloudflare DNS

    - name: Update Cloudflare DNS

      env:

        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}


      run: |


        python update_dns.py





    # 上传结果

    - name: Upload results

      uses: actions/upload-artifact@v4


      with:


        name: ip-results


        path: |


          IPlist.txt

          Senflare.txt

          IPlist-Pro.txt

          Senflare-Pro.txt

          Ranking.txt

          IPtest.log

          Cache.json

          result.csv





    # 保存更新

    - name: Commit results

      run: |


        git config --local user.email "action@github.com"


        git config --local user.name "GitHub Action"



        git add .



        git diff --staged --quiet || git commit -m "Auto update CF IP $(date)"



        git push
