name: IP Test


on:

  schedule:

    # 每3小时运行一次

    - cron: '0 */3 * * *'


  workflow_dispatch:



jobs:


  collect-ips:


    runs-on: ubuntu-latest


    permissions:

      contents: write



    steps:



    # 拉取仓库代码

    - name: Checkout code

      uses: actions/checkout@v4



    # 设置Python环境

    - name: Set up Python

      uses: actions/setup-python@v5

      with:

        python-version: '3.11'



    # 安装依赖

    - name: Install Python dependencies

      run: |

        python -m pip install --upgrade pip

        pip install requests urllib3



    # 运行Senflare-IP

    - name: Run IP Test

      run: |

        python IPtest.py



    # 下载CloudflareSpeedTest

    - name: Install CloudflareSpeedTest

      run: |

        wget -N https://github.com/XIU2/CloudflareSpeedTest/releases/latest/download/cfst_linux_amd64.tar.gz


        tar -zxf cfst_linux_amd64.tar.gz


        echo "===== 解压文件列表 ====="


        ls -al



    # 运行CloudflareSpeedTest

    - name: Run CloudflareSpeedTest

      run: |


        chmod +x cfst || true

        chmod +x CloudflareST || true



        if [ -f "./cfst" ]; then


          echo "使用 cfst"


          ./cfst \
          -f IPlist-Pro.txt \
          -o result.csv \
          -t 20



        elif [ -f "./CloudflareST" ]; then


          echo "使用 CloudflareST"



          ./CloudflareST \
          -f IPlist-Pro.txt \
          -o result.csv \
          -t 20



        else


          echo "错误：没有找到测速程序"


          exit 1


        fi




    # 上传测试结果

    - name: Upload results

      uses: actions/upload-artifact@v4


      with:

        name: ip-results


        path: |


          IPlist.txt

          Senflare.txt

          IPlist-Pro.txt

          Senflare-Pro.txt

          Ranking.txt

          IPtest.log

          Cache.json

          result.csv




    # 提交结果

    - name: Commit results

      run: |


        git config --local user.email "action@github.com"


        git config --local user.name "GitHub Action"



        git add .



        git diff --staged --quiet || git commit -m "Update IP results $(date)"



        git push
